### ISSUE TITLE
Using HiFi reads in the mitoVGP pipeline

### ISSUE THREAD

**Issue by fgcilingir** [gf777/mitoVGP#3]
Hello,

Thank you very much for such a powerful tool. It's very exciting to read more about the potential of fishing out mtDNA reads from WGS data and eventually have even better assemblies.

I have ~ 20x HiFi data from an animal species for its nuclear genome assembly and I was wondering if it is possible to use this type of input data within the mitoVGP pipeline. Apparently, the initial bottleneck of my first trial was the step of polishing with Arrow. Given that I already start with consensus sequences, is there any way to skip the Arrow polishing step in the pipeline? Or do you have any other suggestions regarding the use of HiFi reads?

Thanks for your reply in advance.

**Comment by gf777** [comment]
Dear @fgcilingir,

no, this is tailored to CLR/ONT data. Please have a look at https://github.com/marcelauliano/MitoHiFi if you have Hifi reads
