### ISSUE TITLE
[E::hts_open_format] Failed to open file 

### ISSUE THREAD

**Issue by mcurto** [gf777/mitoVGP#4]
I am trying to run mitoVGP for nanopore this way:

./mitoVGP_bash -a ONT -s Silurus_glanis -i fSilGla1 -r /data/GenomesNanopore/Siluro/Final_results/mitogenome/Sglanis_reference.fasta -1 /data/GenomesNanopore/Siluro/Final_results/mitogenome/List_fastq.txt -t 10

And I am getting the error message bellow:

"[E::hts_open_format] Failed to open file Silurus_glanis/fSilGla1/assembly_MT_rockefeller/intermediates/tgs_bam/aligned_*.bam
samtools view: failed to open "Silurus_glanis/fSilGla1/assembly_MT_rockefeller/intermediates/tgs_bam/aligned_*.bam" for reading: No such file or directory
cat: 'Silurus_glanis/fSilGla1/assembly_MT_rockefeller/intermediates/tgs_MT_extracted_reads/*.int.fastq': No such file or directory

no reads extracted."

It looks like it is not running minimap or reading my file.

As a note, since I am working on ubuntu, I had to edit the mitoVGP so the script would run with bash. I did that by replacing "sh" by "bash".

Thanks,
Manuel

**Comment by gf777** [comment]
The pipeline seems to be running fine, but no reads are extracted. Please paste the full log as it seems that the issue, if any, is occurring upstream

**Comment by mcurto** [comment]
Here it goes
[mitoVGP_error-message_2022-01-21.txt](https://github.com/gf777/mitoVGP/files/7888269/mitoVGP_error-message_2022-01-21.txt)

**Comment by gf777** [comment]
Thanks. It's kind of weird because it looks like it's not doing anything at the minimap2 stage (I would assume some kind of trace even if no read was extracted). These are the lines I am referring to https://github.com/gf777/mitoVGP/blob/master/scripts/mtDNApipe#L242

Generally speaking, it is possible in some datasets that there are absolutely no MT reads, but usually at least a few should be present and you shouldn't get that error (but even then, I think the output file should still exist, so the error is still weird). Isn't that you commented out the minimap lines?

**Comment by mcurto** [comment]
Hi again.
I downloaded the program again and I continue to have the same error. I have used minimap on this data with a reference mitochondira genome and there were reads mapping. Besides the error message is almost instantaneous so, I think it is not even trying to map the reads.
I also tried to run the example provided by you: "./mitoVGP -a ONT -s Mastacembelus_armatus -i fMasArm1 -r mtDNA_Mastacembelus_armatus.fasta -t 10 -b variantCaller". And in this case there is no problem.
So I think the program is not reading the fastq file for some reason. Does the file containing the path to the fastq need to be in a specific format?
Best,
Manuel

**Comment by gf777** [comment]
You are right https://github.com/gf777/mitoVGP/blob/db91a01f1aa5ebe0c5ef82b2a57feac82d335a4e/scripts/mtDNApipe#L214 wasn't accepting gzip compressed reads. Please try again now it should work. Thanks

**Comment by mcurto** [comment]
Thanks. That worked. However now I am having a problem in the polishing part with medaka. Should I open a new issue? The log file with the error is attached
[fSilGla1_2022-01-20.log.txt](https://github.com/gf777/mitoVGP/files/7919154/fSilGla1_2022-01-20.log.txt)
.

**Comment by gf777** [comment]
Great. Yes please open a new issue, Ill close this one!
