### ISSUE TITLE
Location of input files

### ISSUE THREAD

**Issue by usmart31** [gf777/mitoVGP#8]
Hi,

This is my first time using the pipeline. I ran the example dataset successfully, but am wondering how I can run my own files through mitoVGP, since it appears that the input files need to already have a mitoVGP ID and need to be on the AWS server.  Any clarification would be greatly appreciated! 

Thanks

**Comment by gf777** [comment]
Hello @usmart31 
Thanks for reaching out. There are a bunch of options for local files: https://github.com/gf777/mitoVGP/blob/master/mitoVGP#L43
The ID can be anything
All the best
Giulio

**Comment by usmart31** [comment]
Got it, thanks for the quick response Giulio! 
Best,
Utpal
